version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:9.5
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - nestjs-order-management

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4:4.26
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - nestjs-order-management

  redis:
    container_name: redis
    image: redis:6.0
    ports:
      - "6379:6379"
    networks:
      - nestjs-order-management

networks:
  nestjs-order-management:
    driver: bridge
